project: dtt
save_path: /path/to/save/checkpoints
name: dtt-gsm

only_eval: False

# Model configuration
dtt: True
cot: False
no_thoughts: False
no_cot: False

# DTT specific configuration
use_grpo: True
kl_coef: 0.04
clip_range: 0.2
group_size: 8

# Latent reasoning configuration
c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

# Training configuration
save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: /path/to/data/gsm_train.json
val_path: /path/to/data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
steps_per_epoch: 100
lr: !!float "1e-4"
weight_decay: 0.01
