# need 4 gpus

project: DTT
save_path: DTT_GSM
name: gsm-dtt-eval

only_eval: True

save_only_improve: False
model_id: openai-community/gpt2
load_model_path: DTT_GSM  # Replace with actual DTT checkpoint path
seed: 0
resume: 15
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_test.json
per_device_train_batch_size: 16
debug: False
gradient_accumulation_steps: 2
num_train_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01
save_steps: 500
eval_steps: 500