# need 4 gpus

project: DTT
save_path: DTT_Pros_QA
name: prosqa-dtt

only_eval: False

save_only_improve: False
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
debug: False
per_device_train_batch_size: 1    # Each GPU processes 1 input per step
gradient_accumulation_steps: 32    # Accumulate over 8 steps 
num_generations: 16               # Generate 16 trajectories per input
num_train_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01
save_steps: 500
eval_steps: 500