dataset: gsm8k
batch_size: 32  # Per GPU
accum_steps: 1  # For effective batch_size=32 (4 GPUs × 4 samples × 2 accumulations)
epochs: 2
lr: 1.0e-5
lambda_gate: 0.1
group_size: 8
epsilon: 0.2
beta_kl: 0.01
max_length: 512
val_size: 256
data_dir: data